services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/config:/config
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: "neo4j/neo4jpassword"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always